In [1]:
import itertools
import numpy as np

odds = [1,2,3,4]
evens = [2,4,6]

# The function 'permutes' all evens and odds and pairs each together pairwise
# Given a parameter 'shape' (x, y), where x is the number of rows and
# y is the number of columns.
def pathchecker(shape):
    path_positions = []
    # Note that, for the sake of efficiency, we loop through the POSITIONS 
    # of the odds and evens.
    size = shape[0] * shape[1]
    # (size+1)// 2 is size/2 for even, and size//2 is (size-1)/2 for odd - 
    # the upper bound conditions are satisfied
    for i in list(itertools.permutations(2*np.arange((size+1)//2)+1)):
        for j in list(itertools.permutations(2*(1+np.arange(size//2)))):
            # Interweave the two arrays

            ## Original:
            #iw = [val for pair in zip(i, j) for val in pair]

            
            ## Update:
            # ** odd & even column size cases:
            if shape[1] % 2 == 1:
                iw = [val for pair in zip(i, j) for val in pair]
            else:
                iw = []
                odd_next = True
                for row in range(shape[0]):
                    for col in range(shape[1]):
                        if odd_next:
                            iw.append(i[(shape[0]*row + col)//2])
                        else:
                            iw.append(j[(shape[0]*row + col)//2])
                        odd_next = not odd_next
                    odd_next = not odd_next
            
            if len(i) > len(j):
                iw.append(i[-1])
            #print(iw)
            valid = True
            # Check if each position is adjacent to the previous
            for k in range(len(iw)-1):
                if not(((iw[k+1] == iw[k]+1) and (iw[k] % shape[1] != 0)) or ((iw[k+1] == iw[k]-1) and (iw[k] % shape[1] != 1)) or (iw[k+1] == iw[k]+shape[1]) or (iw[k+1] == iw[k]-shape[1])):
                    valid = False
                    break
            if valid:
                path_positions.append(iw)
    return path_positions                    

# Map each position to a grid point
def draw(positions,shape):
    array = np.empty(shape)
    for i, pos in enumerate(positions):
        array[(pos-1) // shape[1], (pos-1) % shape[1]] = i+1
    return array
    
print("Valid 2x2 grids:", pathchecker([2,2]))
print("No. of 2x3 grids:", 2*len(pathchecker([2,3])))
print("No. of 3x3 grids:", len(pathchecker([3,3])))

Valid 2x2 grids: [[1, 2, 4, 3], [3, 4, 2, 1]]
No. of 2x3 grids: 16
No. of 3x3 grids: 40


In [2]:
for i, arr in enumerate(pathchecker([3,3])):
    print(draw(arr, [3,3]), "\n")

[[1. 2. 3.]
 [6. 5. 4.]
 [7. 8. 9.]] 

[[1. 2. 3.]
 [8. 7. 4.]
 [9. 6. 5.]] 

[[1. 2. 3.]
 [8. 9. 4.]
 [7. 6. 5.]] 

[[1. 4. 5.]
 [2. 3. 6.]
 [9. 8. 7.]] 

[[1. 2. 9.]
 [4. 3. 8.]
 [5. 6. 7.]] 

[[1. 6. 7.]
 [2. 5. 8.]
 [3. 4. 9.]] 

[[1. 8. 7.]
 [2. 9. 6.]
 [3. 4. 5.]] 

[[1. 8. 9.]
 [2. 7. 6.]
 [3. 4. 5.]] 

[[3. 2. 1.]
 [4. 5. 6.]
 [9. 8. 7.]] 

[[3. 2. 1.]
 [4. 7. 8.]
 [5. 6. 9.]] 

[[3. 2. 1.]
 [4. 9. 8.]
 [5. 6. 7.]] 

[[5. 4. 1.]
 [6. 3. 2.]
 [7. 8. 9.]] 

[[9. 2. 1.]
 [8. 3. 4.]
 [7. 6. 5.]] 

[[7. 6. 1.]
 [8. 5. 2.]
 [9. 4. 3.]] 

[[7. 8. 1.]
 [6. 9. 2.]
 [5. 4. 3.]] 

[[9. 8. 1.]
 [6. 7. 2.]
 [5. 4. 3.]] 

[[3. 4. 5.]
 [2. 1. 6.]
 [9. 8. 7.]] 

[[3. 2. 9.]
 [4. 1. 8.]
 [5. 6. 7.]] 

[[5. 4. 3.]
 [6. 1. 2.]
 [7. 8. 9.]] 

[[9. 2. 3.]
 [8. 1. 4.]
 [7. 6. 5.]] 

[[5. 6. 7.]
 [4. 1. 8.]
 [3. 2. 9.]] 

[[9. 8. 7.]
 [2. 1. 6.]
 [3. 4. 5.]] 

[[7. 6. 5.]
 [8. 1. 4.]
 [9. 2. 3.]] 

[[7. 8. 9.]
 [6. 1. 2.]
 [5. 4. 3.]] 

[[3. 4. 5.]
 [2. 7. 6.]
 [1. 8. 9.]] 

[[3. 4. 5.]
 [2. 9. 6.]
 

In [3]:
# Testing
shape = [4,4]
i = [1,3,5,7,9,11,13,15]
j = [2,4,6,8,10,12,14,16]
iw = []
odd_next = True
for row in range(shape[0]):
    for col in range(shape[1]):
        if odd_next:
            iw.append(i[(shape[0]*row + col)//2])
        else:
            iw.append(j[(shape[0]*row + col)//2])
        odd_next = not odd_next
    odd_next = not odd_next
print(iw)
draw(iw, [4,4])

[1, 2, 3, 4, 6, 5, 8, 7, 9, 10, 11, 12, 14, 13, 16, 15]


array([[ 1.,  2.,  3.,  4.],
       [ 6.,  5.,  8.,  7.],
       [ 9., 10., 11., 12.],
       [14., 13., 16., 15.]])